### ISSUE TITLE
Can't find subtitles for 'Heroes Reborn' series

### ISSUE THREAD

**Issue by Md-Cake** [same31/addic7ed-api#1]
Greetings,

I can't find any subtitles for 'Heroes Reborn' series using your lib. It seems like there is problem with it since there is 'Heroes Reborn: Dark Matters' series which is found when I'm trying to search it directly on addic7ed.com. Can you fix it somehow?

**Comment by same31** [comment]
Hi,

Thank you for submitting the bug.

Actually, there is a name conflict between these two shows.

I tried with 'Heroes Reborn S01E01' search string and the first result was 'Heroes Reborn', second one was 'Dark Matters'

So I fixed it in v1.1.0 by following the first result found by addic7ed.com.
