### ISSUE TITLE
Shows page broken since now login is required

### ISSUE THREAD

**Issue by bennieboj** [same31/addic7ed-api#10]
https://www.addic7ed.com/shows.php can now only be requested while logged in.
`getShowTitles()` uses this page and since we're not logged in it now always returns the [shows on the bottom of the login page...](https://i.imgur.com/gE6rU2U.png)

Which action should we take?
 - Implement a login (hard due to recaptcha)
 - Remove the functionality since at this moment it's not functioning as expected.
_Edit:_
 - _Never mind, I found another way to the same data: the main page has a dropdown with all shows, I'll just parse that ;)_

**Comment by same31** [comment]
Thank you for your investigation and contribution, much appreciated!
