### ISSUE TITLE
Search page moved

### ISSUE THREAD

**Issue by bennieboj** [same31/addic7ed-api#15]
The search page has been moved, check for yourself:
[https://www.addic7ed.com/search.php?search=Mayans+MC&Submit=Search](https://www.addic7ed.com/search.php?search=Mayans+MC&Submit=Search)
[https://www.addic7ed.com/srch.php?search=Mayans+MC&Submit=Search](https://www.addic7ed.com/srch.php?search=Mayans+MC&Submit=Search)

**Comment by same31** [comment]
Thank you!
